---
- name: Check Uptime
  hosts: test-servers
  gather_facts: true
  become: yes  # If sudo privileges are required
  become_user: root
  become_method: sudo
  tasks:
    - name: Get Uptime
      command: /usr/bin/uptime
      register: uptime_result

    - name: Display Uptime
      debug:
        var: uptime_result.stdout_lines
